ALTER TABLE notifications
DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE notifications
ADD CONSTRAINT notifications_type_check CHECK (type IN (
    'BOOK_RESERVED',
    'BOOK_AVAILABLE',
    'BORROW_SUCCESS',
    'BORROW_CANCELLED_EXPIRED',
    'RESERVATION_EXPIRED',
    'OVERDUE_WARNING',
    'FINE_ISSUED',
    'SYSTEM_MAINTENANCE',
    'RETURN_REMINDER',
    'PICKUP_CONFIRMED',
    'RETURN_CONFIRMED',
    'FINE_PAID',
    'REVIEW_HELPFUL',
    'REVIEW_REPLY'
));
