-- Enrich catalogue categories around the 11 faculties used by AI audience
-- classification. Faculty rows are broad parent categories; each has roughly
-- 10 narrower child categories for librarian classification and browsing.

WITH source(id, name, bio, parent_name) AS (
    VALUES
        (760210001, 'Khoa Khoa Học Và Kỹ Thuật Máy Tính', 'Nhóm danh mục cho khoa học máy tính, kỹ thuật phần mềm, dữ liệu và hệ thống thông tin.', NULL),
        (760210002, 'Khoa Điện - Điện Tử', 'Nhóm danh mục cho điện, điện tử, viễn thông, điều khiển và hệ thống nhúng.', NULL),
        (760210003, 'Khoa Cơ Khí', 'Nhóm danh mục cho cơ khí, chế tạo, robot, tự động hóa và hệ thống cơ điện tử.', NULL),
        (760210004, 'Khoa Kỹ Thuật Hóa Học', 'Nhóm danh mục cho hóa học, kỹ thuật hóa học, công nghệ sinh học và quá trình công nghiệp.', NULL),
        (760210005, 'Khoa Kỹ Thuật Xây Dựng', 'Nhóm danh mục cho xây dựng, kết cấu, vật liệu, địa kỹ thuật và quản lý công trình.', NULL),
        (760210006, 'Khoa Kỹ Thuật Giao Thông', 'Nhóm danh mục cho giao thông, vận tải, logistics, hạ tầng và an toàn giao thông.', NULL),
        (760210007, 'Khoa Quản Lý Công Nghiệp', 'Nhóm danh mục cho quản trị, vận hành, tài chính, marketing và quản lý sản xuất.', NULL),
        (760210008, 'Khoa Môi Trường Và Tài Nguyên', 'Nhóm danh mục cho môi trường, tài nguyên nước, khí hậu và phát triển bền vững.', NULL),
        (760210009, 'Khoa Công Nghệ Vật Liệu', 'Nhóm danh mục cho vật liệu kim loại, polymer, composite, bán dẫn và vật liệu tiên tiến.', NULL),
        (760210010, 'Khoa Khoa Học Ứng Dụng', 'Nhóm danh mục cho toán, thống kê, vật lý, mô phỏng và khoa học tính toán.', NULL),
        (760210011, 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí', 'Nhóm danh mục cho địa chất, dầu khí, địa vật lý, khoan khai thác và tài nguyên khoáng sản.', NULL),

        (760211001, 'Lập Trình Cơ Bản', 'Nhập môn lập trình, tư duy thuật toán và kỹ thuật viết chương trình.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211002, 'Lập Trình Nâng Cao', 'Kỹ thuật lập trình nâng cao, mô hình hóa và xử lý bài toán phức tạp.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211003, 'Cấu Trúc Dữ Liệu Và Giải Thuật', 'Cấu trúc dữ liệu, giải thuật, độ phức tạp và tối ưu thuật toán.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211004, 'Kỹ Thuật Phần Mềm', 'Quy trình phát triển, kiểm thử, bảo trì và quản lý chất lượng phần mềm.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211005, 'Kiến Trúc Và Thiết Kế Hệ Thống', 'Kiến trúc phần mềm, thiết kế hệ thống, mẫu thiết kế và khả năng mở rộng.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211006, 'Cơ Sở Dữ Liệu Và Kho Dữ Liệu', 'Cơ sở dữ liệu quan hệ, NoSQL, kho dữ liệu, truy vấn và giao dịch.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211007, 'Trí Tuệ Nhân Tạo Và Học Máy', 'AI, học máy, học sâu, mô hình dự đoán và ứng dụng thông minh.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211008, 'Mạng Máy Tính Và An Toàn Thông Tin', 'Mạng, giao thức, bảo mật, mã hóa và phòng thủ hệ thống.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211009, 'Hệ Điều Hành Và Hệ Phân Tán', 'Hệ điều hành, tiến trình, bộ nhớ, hệ phân tán và điện toán đám mây.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),
        (760211010, 'Tương Tác Người Máy Và Đồ Họa', 'HCI, đồ họa máy tính, trực quan hóa và trải nghiệm người dùng.', 'Khoa Khoa Học Và Kỹ Thuật Máy Tính'),

        (760212001, 'Mạch Điện', 'Phân tích mạch điện, linh kiện, công suất và hệ thống điện cơ bản.', 'Khoa Điện - Điện Tử'),
        (760212002, 'Điện Tử Tương Tự', 'Mạch tương tự, khuếch đại, lọc tín hiệu và linh kiện bán dẫn.', 'Khoa Điện - Điện Tử'),
        (760212003, 'Điện Tử Số', 'Logic số, FPGA, vi xử lý và thiết kế hệ thống số.', 'Khoa Điện - Điện Tử'),
        (760212004, 'Xử Lý Tín Hiệu', 'Tín hiệu, hệ thống, biến đổi Fourier, lọc và xử lý số.', 'Khoa Điện - Điện Tử'),
        (760212005, 'Viễn Thông', 'Truyền thông số, mạng viễn thông, anten và hệ thống vô tuyến.', 'Khoa Điện - Điện Tử'),
        (760212006, 'Hệ Thống Nhúng', 'Vi điều khiển, firmware, cảm biến, giao tiếp ngoại vi và IoT.', 'Khoa Điện - Điện Tử'),
        (760212007, 'Điều Khiển Tự Động', 'Mô hình hóa hệ thống, điều khiển phản hồi, PID và ổn định.', 'Khoa Điện - Điện Tử'),
        (760212008, 'Điện Công Suất', 'Bộ biến đổi công suất, truyền động điện và hệ thống năng lượng.', 'Khoa Điện - Điện Tử'),
        (760212009, 'Hệ Thống Năng Lượng', 'Lưới điện, năng lượng tái tạo, phân phối và quản lý điện năng.', 'Khoa Điện - Điện Tử'),
        (760212010, 'Thiết Kế Vi Mạch', 'Thiết kế IC, VLSI, CMOS, kiểm chứng và quy trình chế tạo chip.', 'Khoa Điện - Điện Tử'),

        (760213001, 'Cơ Học Kỹ Thuật', 'Tĩnh học, động lực học, sức bền vật liệu và cơ học ứng dụng.', 'Khoa Cơ Khí'),
        (760213002, 'Nguyên Lý Máy', 'Cơ cấu máy, truyền động, động học và phân tích chuyển động.', 'Khoa Cơ Khí'),
        (760213003, 'Chi Tiết Máy', 'Thiết kế chi tiết máy, trục, ổ, bánh răng và mối ghép.', 'Khoa Cơ Khí'),
        (760213004, 'Công Nghệ Chế Tạo Máy', 'Gia công, quy trình chế tạo, dụng cụ cắt và tối ưu sản xuất.', 'Khoa Cơ Khí'),
        (760213005, 'CAD CAM CNC', 'Thiết kế CAD, lập trình CAM, gia công CNC và mô phỏng chế tạo.', 'Khoa Cơ Khí'),
        (760213006, 'Robot Và Cơ Điện Tử', 'Robot, cơ điện tử, cảm biến, truyền động và điều khiển chuyển động.', 'Khoa Cơ Khí'),
        (760213007, 'Kỹ Thuật Nhiệt', 'Nhiệt động lực học, truyền nhiệt, lạnh và hệ thống nhiệt.', 'Khoa Cơ Khí'),
        (760213008, 'Cơ Học Chất Lỏng', 'Dòng chảy, thủy lực, khí động học và máy thủy khí.', 'Khoa Cơ Khí'),
        (760213009, 'Kỹ Thuật Ô Tô', 'Động cơ, khung gầm, hệ thống điện và chẩn đoán ô tô.', 'Khoa Cơ Khí'),
        (760213010, 'Quản Lý Bảo Trì Công Nghiệp', 'Bảo trì, độ tin cậy, TPM và quản lý thiết bị công nghiệp.', 'Khoa Cơ Khí'),

        (760214001, 'Hóa Đại Cương', 'Cấu tạo chất, liên kết hóa học, cân bằng và phản ứng hóa học.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214002, 'Hóa Hữu Cơ', 'Hợp chất hữu cơ, cơ chế phản ứng, tổng hợp và phân tích cấu trúc.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214003, 'Hóa Phân Tích', 'Phân tích định tính, định lượng, phổ học và sắc ký.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214004, 'Hóa Lý', 'Nhiệt động hóa học, động học, điện hóa và cân bằng pha.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214005, 'Quá Trình Và Thiết Bị', 'Truyền nhiệt, truyền khối, thiết bị phản ứng và tách chất.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214006, 'Kỹ Thuật Phản Ứng', 'Thiết kế phản ứng, động học, xúc tác và mô hình hóa reactor.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214007, 'Công Nghệ Polymer', 'Polymer, vật liệu nhựa, tổng hợp và gia công polymer.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214008, 'Công Nghệ Thực Phẩm', 'Quá trình thực phẩm, bảo quản, an toàn và công nghệ chế biến.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214009, 'Công Nghệ Sinh Học', 'Sinh học phân tử, vi sinh, enzyme và ứng dụng công nghệ sinh học.', 'Khoa Kỹ Thuật Hóa Học'),
        (760214010, 'An Toàn Hóa Chất', 'An toàn phòng thí nghiệm, độc chất, quản lý rủi ro và môi trường hóa chất.', 'Khoa Kỹ Thuật Hóa Học'),

        (760215001, 'Cơ Học Kết Cấu', 'Phân tích kết cấu, tải trọng, nội lực và biến dạng công trình.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215002, 'Bê Tông Cốt Thép', 'Thiết kế cấu kiện bê tông cốt thép, tiêu chuẩn và kiểm toán kết cấu.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215003, 'Kết Cấu Thép', 'Thiết kế kết cấu thép, liên kết, ổn định và nhà công nghiệp.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215004, 'Địa Kỹ Thuật', 'Cơ học đất, nền móng, khảo sát địa chất và xử lý nền.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215005, 'Vật Liệu Xây Dựng', 'Xi măng, bê tông, vật liệu hoàn thiện và kiểm định vật liệu.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215006, 'Thi Công Công Trình', 'Tổ chức thi công, máy xây dựng, biện pháp và tiến độ công trình.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215007, 'Quản Lý Dự Án Xây Dựng', 'Chi phí, tiến độ, hợp đồng, rủi ro và quản lý dự án xây dựng.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215008, 'Cấp Thoát Nước', 'Hệ thống cấp nước, thoát nước, xử lý nước và hạ tầng đô thị.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215009, 'Cầu Đường', 'Thiết kế cầu, đường, mặt đường và công trình giao thông.', 'Khoa Kỹ Thuật Xây Dựng'),
        (760215010, 'Mô Hình BIM', 'BIM, phối hợp thiết kế, quản lý thông tin và số hóa công trình.', 'Khoa Kỹ Thuật Xây Dựng'),

        (760216001, 'Quy Hoạch Giao Thông', 'Quy hoạch mạng lưới, nhu cầu đi lại và tổ chức giao thông đô thị.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216002, 'Kỹ Thuật Đường Bộ', 'Thiết kế đường, vật liệu mặt đường, khai thác và bảo trì đường bộ.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216003, 'Kỹ Thuật Cầu Hầm', 'Thiết kế cầu, hầm, kết cấu giao thông và kiểm định công trình.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216004, 'Vận Tải Và Logistics', 'Quản lý vận tải, logistics, kho bãi và chuỗi cung ứng.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216005, 'Kỹ Thuật Hàng Hải', 'Tàu thủy, cảng biển, vận tải biển và an toàn hàng hải.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216006, 'Kỹ Thuật Hàng Không', 'Khí động học, kết cấu máy bay, khai thác và an toàn hàng không.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216007, 'An Toàn Giao Thông', 'Phân tích tai nạn, tổ chức giao thông và giải pháp an toàn.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216008, 'Giao Thông Thông Minh', 'ITS, cảm biến, dữ liệu giao thông và điều khiển thông minh.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216009, 'Khai Thác Cảng', 'Quản lý cảng, bốc xếp, điều độ và khai thác hạ tầng cảng.', 'Khoa Kỹ Thuật Giao Thông'),
        (760216010, 'Kinh Tế Vận Tải', 'Chi phí vận tải, định giá, tối ưu tuyến và hiệu quả khai thác.', 'Khoa Kỹ Thuật Giao Thông'),

        (760217001, 'Quản Trị Vận Hành', 'Vận hành, quy trình, năng suất và cải tiến hệ thống sản xuất.', 'Khoa Quản Lý Công Nghiệp'),
        (760217002, 'Quản Lý Sản Xuất', 'Hoạch định sản xuất, điều độ, tồn kho và kiểm soát năng lực.', 'Khoa Quản Lý Công Nghiệp'),
        (760217003, 'Quản Lý Chất Lượng', 'QC, QA, Six Sigma, tiêu chuẩn chất lượng và cải tiến liên tục.', 'Khoa Quản Lý Công Nghiệp'),
        (760217004, 'Chuỗi Cung Ứng', 'Mua hàng, logistics, tồn kho, phân phối và thiết kế chuỗi cung ứng.', 'Khoa Quản Lý Công Nghiệp'),
        (760217005, 'Phân Tích Kinh Doanh', 'Business analytics, dữ liệu quản trị, dashboard và ra quyết định.', 'Khoa Quản Lý Công Nghiệp'),
        (760217006, 'Tài Chính Doanh Nghiệp', 'Tài chính, vốn, đầu tư, định giá và quản trị rủi ro tài chính.', 'Khoa Quản Lý Công Nghiệp'),
        (760217007, 'Marketing Công Nghiệp', 'Marketing B2B, nghiên cứu thị trường và chiến lược thương hiệu.', 'Khoa Quản Lý Công Nghiệp'),
        (760217008, 'Quản Trị Nhân Sự', 'Tuyển dụng, đào tạo, đánh giá hiệu suất và văn hóa tổ chức.', 'Khoa Quản Lý Công Nghiệp'),
        (760217009, 'Khởi Nghiệp Công Nghệ', 'Mô hình kinh doanh, đổi mới sáng tạo, sản phẩm và gọi vốn.', 'Khoa Quản Lý Công Nghiệp'),
        (760217010, 'Kinh Tế Kỹ Thuật', 'Phân tích chi phí, hiệu quả dự án, tối ưu nguồn lực và đầu tư.', 'Khoa Quản Lý Công Nghiệp'),

        (760218001, 'Kỹ Thuật Môi Trường', 'Xử lý ô nhiễm, công nghệ môi trường và kiểm soát chất thải.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218002, 'Quản Lý Tài Nguyên Nước', 'Thủy văn, tài nguyên nước, cấp thoát nước và quản lý lưu vực.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218003, 'Xử Lý Nước Thải', 'Công nghệ xử lý nước thải, bùn thải và vận hành hệ thống.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218004, 'Quản Lý Chất Thải Rắn', 'Thu gom, tái chế, xử lý chất thải rắn và kinh tế tuần hoàn.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218005, 'Ô Nhiễm Không Khí', 'Nguồn thải, lan truyền, quan trắc và kiểm soát ô nhiễm không khí.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218006, 'Biến Đổi Khí Hậu', 'Khí hậu, thích ứng, giảm phát thải và đánh giá rủi ro khí hậu.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218007, 'Đánh Giá Tác Động Môi Trường', 'EIA, quản lý rủi ro, pháp luật và giám sát môi trường.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218008, 'GIS Và Viễn Thám', 'GIS, ảnh vệ tinh, phân tích không gian và bản đồ tài nguyên.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218009, 'Sinh Thái Ứng Dụng', 'Hệ sinh thái, đa dạng sinh học, phục hồi và quản lý bảo tồn.', 'Khoa Môi Trường Và Tài Nguyên'),
        (760218010, 'Phát Triển Bền Vững', 'Kinh tế xanh, ESG, mục tiêu bền vững và quản trị tài nguyên.', 'Khoa Môi Trường Và Tài Nguyên'),

        (760219001, 'Vật Liệu Kim Loại', 'Kim loại, hợp kim, nhiệt luyện, ăn mòn và cơ tính vật liệu.', 'Khoa Công Nghệ Vật Liệu'),
        (760219002, 'Vật Liệu Polymer', 'Polymer, nhựa, cao su, gia công và tính chất vật liệu mềm.', 'Khoa Công Nghệ Vật Liệu'),
        (760219003, 'Vật Liệu Composite', 'Composite nền polymer, sợi gia cường, thiết kế và chế tạo.', 'Khoa Công Nghệ Vật Liệu'),
        (760219004, 'Vật Liệu Gốm', 'Gốm kỹ thuật, thủy tinh, vật liệu chịu nhiệt và công nghệ nung.', 'Khoa Công Nghệ Vật Liệu'),
        (760219005, 'Vật Liệu Bán Dẫn', 'Bán dẫn, linh kiện điện tử, công nghệ màng mỏng và vi cấu trúc.', 'Khoa Công Nghệ Vật Liệu'),
        (760219006, 'Công Nghệ Nano', 'Vật liệu nano, tổng hợp, đặc trưng và ứng dụng nano.', 'Khoa Công Nghệ Vật Liệu'),
        (760219007, 'Phân Tích Vật Liệu', 'XRD, SEM, TEM, phổ học và kiểm định cấu trúc vật liệu.', 'Khoa Công Nghệ Vật Liệu'),
        (760219008, 'Vật Liệu Năng Lượng', 'Pin, nhiên liệu, vật liệu lưu trữ năng lượng và xúc tác.', 'Khoa Công Nghệ Vật Liệu'),
        (760219009, 'Ăn Mòn Và Bảo Vệ Vật Liệu', 'Ăn mòn, phủ bảo vệ, điện hóa và kéo dài tuổi thọ vật liệu.', 'Khoa Công Nghệ Vật Liệu'),
        (760219010, 'Tái Chế Vật Liệu', 'Tái chế kim loại, polymer, chất thải vật liệu và kinh tế tuần hoàn.', 'Khoa Công Nghệ Vật Liệu'),

        (760220001, 'Giải Tích', 'Giới hạn, đạo hàm, tích phân, chuỗi và ứng dụng kỹ thuật.', 'Khoa Khoa Học Ứng Dụng'),
        (760220002, 'Đại Số Tuyến Tính', 'Ma trận, không gian vector, trị riêng và ứng dụng tính toán.', 'Khoa Khoa Học Ứng Dụng'),
        (760220003, 'Xác Suất Thống Kê', 'Xác suất, thống kê suy luận, mô hình ngẫu nhiên và dữ liệu.', 'Khoa Khoa Học Ứng Dụng'),
        (760220004, 'Phương Trình Vi Phân', 'ODE, PDE, mô hình động lực và nghiệm số.', 'Khoa Khoa Học Ứng Dụng'),
        (760220005, 'Tối Ưu Hóa Ứng Dụng', 'Tối ưu tuyến tính, phi tuyến, ràng buộc và thuật toán tối ưu.', 'Khoa Khoa Học Ứng Dụng'),
        (760220006, 'Vật Lý Đại Cương', 'Cơ, nhiệt, điện từ, quang học và vật lý hiện đại.', 'Khoa Khoa Học Ứng Dụng'),
        (760220007, 'Vật Lý Kỹ Thuật', 'Vật lý ứng dụng trong điện tử, vật liệu, năng lượng và đo lường.', 'Khoa Khoa Học Ứng Dụng'),
        (760220008, 'Mô Phỏng Số', 'Phương pháp số, mô phỏng, tính toán khoa học và phần mềm kỹ thuật.', 'Khoa Khoa Học Ứng Dụng'),
        (760220009, 'Toán Rời Rạc', 'Logic, tổ hợp, đồ thị, quan hệ và cấu trúc rời rạc.', 'Khoa Khoa Học Ứng Dụng'),
        (760220010, 'Khoa Học Tính Toán', 'Tính toán hiệu năng, mô hình hóa, dữ liệu khoa học và thuật toán số.', 'Khoa Khoa Học Ứng Dụng'),

        (760221001, 'Địa Chất Đại Cương', 'Khoáng vật, thạch học, kiến tạo và lịch sử địa chất.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221002, 'Địa Chất Công Trình', 'Khảo sát nền móng, địa chất công trình và rủi ro địa kỹ thuật.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221003, 'Địa Vật Lý', 'Phương pháp địa vật lý, đo đạc, xử lý tín hiệu và minh giải.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221004, 'Khoáng Sản', 'Tài nguyên khoáng sản, thăm dò, đánh giá trữ lượng và khai thác.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221005, 'Địa Chất Dầu Khí', 'Bể trầm tích, hệ thống dầu khí, nguồn chứa và đánh giá triển vọng.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221006, 'Khoan Dầu Khí', 'Công nghệ khoan, dung dịch khoan, thiết kế giếng và an toàn khoan.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221007, 'Khai Thác Dầu Khí', 'Khai thác mỏ dầu khí, dòng chảy trong vỉa và tăng cường thu hồi.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221008, 'Địa Chất Thủy Văn', 'Nước dưới đất, tầng chứa nước, ô nhiễm và quản lý tài nguyên nước.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221009, 'Mô Hình Vỉa', 'Mô hình địa chất, mô phỏng vỉa, dữ liệu giếng và dự báo sản lượng.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí'),
        (760221010, 'An Toàn Dầu Khí', 'An toàn công trình dầu khí, rủi ro, môi trường và ứng phó sự cố.', 'Khoa Kỹ Thuật Địa Chất Và Dầu Khí')
),
resolved AS (
    SELECT
        source.id,
        source.name,
        source.bio,
        parent.id AS parent_id
    FROM source
    LEFT JOIN categories parent ON parent.name = source.parent_name
)
INSERT INTO categories (id, created_at, updated_at, name, bio, parent_category_id)
SELECT id, NOW(), NOW(), name, bio, parent_id
FROM resolved
ON CONFLICT (name) DO UPDATE SET
    bio = EXCLUDED.bio,
    parent_category_id = COALESCE(categories.parent_category_id, EXCLUDED.parent_category_id),
    updated_at = NOW();
