ALTER TABLE notifications
DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE notifications
ADD CONSTRAINT notifications_type_check CHECK (type IN (
    'BOOK_RESERVED',
    'BOOK_AVAILABLE',
    'BORROW_SUCCESS',
    'BORROW_CANCELLED_EXPIRED',
    'RESERVATION_EXPIRED',
    'OVERDUE_WARNING',
    'FINE_ISSUED',
    'SYSTEM_MAINTENANCE',
    'RETURN_REMINDER',
    'PICKUP_CONFIRMED',
    'RETURN_CONFIRMED',
    'FINE_PAID',
    'REVIEW_HELPFUL',
    'REVIEW_REPLY',
    'CONTACT_TICKET_REPLY',
    'CONTACT_TICKET_RESOLVED',
    'CONTACT_TICKET_CLOSED',
    'LIB_CIRC_PICKUP',
    'LIB_CIRC_RETURN',
    'LIB_FINE_PAID',
    'LIB_TICKET_NEW',
    'LIB_TICKET_ASSIGNED',
    'LIB_TICKET_RESOLVED',
    'LIB_TICKET_CLOSED',
    'LIB_TICKET_MESSAGE',
    'LIB_TICKET_FEEDBACK',
    'LIB_REVIEW_NEW',
    'LIB_BOOK_CREATED',
    'LIB_BOOK_UPDATED',
    'LIB_BOOK_DELETED',
    'LIB_COPY_CREATED',
    'LIB_POLICY_UPDATED'
));
