ALTER TABLE publications
    ADD COLUMN IF NOT EXISTS publication_format VARCHAR(40) DEFAULT 'PRINT_BOOK',
    ADD COLUMN IF NOT EXISTS edition_note VARCHAR(255);

ALTER TABLE items
    ADD COLUMN IF NOT EXISTS copy_type VARCHAR(40) DEFAULT 'ORIGINAL',
    ADD COLUMN IF NOT EXISTS binding_type VARCHAR(40) DEFAULT 'UNKNOWN',
    ADD COLUMN IF NOT EXISTS condition_note TEXT,
    ADD COLUMN IF NOT EXISTS acquired_date DATE,
    ADD COLUMN IF NOT EXISTS acquisition_source VARCHAR(120);
